### ISSUE TITLE
Does not handle pushing all tags

### ISSUE THREAD

**Issue by mtrmac** [runcom/rhel-push-plugin#1]
Looking at https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L42 vs. https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.23.md , the `tag` parameter is optional in the API (to push all tags within a repository).  The plugin will silently let through pushes without the `tag` parameter.

**Comment by runcom** [comment]
fixed in master, pls check

**Comment by mtrmac** [comment]
I’m not sure this is sufficient; if omitting the `tag` parameter causes the daemon to push all existing tags within a repository, it seems that the plugin should perform the check on all tags individually, instead of just doing one check with a tag-less name.

Or, I guess, just prohibit the “`tag` missing or empty” calls altogether?

**Comment by runcom** [comment]
> Or, I guess, just prohibit the “tag missing or empty” calls altogether?

seems to bad to do this, I'll check every tag as I assume that's the right thing to do

**Comment by runcom** [comment]
how could you have an image tagged multiple times not inherit the same parent? is it possible? If so, is checking any of the tag safe?

**Comment by mtrmac** [comment]
It is not the same image, just the same repo. AFAIK there is no requirement for the images to share any history; e.g. you could have `mywordpress:loadbalancer`, `mywordpress:mainapplication` and `mywordpress:mariadb` images, all within the `mywordpress` repository but sharing no history (`:loadbalancer` based on Fedora, `mainapplication` based on RHEL and `mariadb` based on Ubuntu`, for example).

It is not how images are _usually_ named and tagged but it is perfectly legal.

**Comment by runcom** [comment]
I'm actually erroring out if any of the tag when pushing all tags is rhel based

fixed in master

**Comment by runcom** [comment]
@mtrmac could you have another fast look? :angel:

**Comment by mtrmac** [comment]
I haven’t deeply reviewed all the API calls, but at least from a quick skim this makes sense.

In the `tag == ""` case, should https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L85 still be called? It seems that this will default to the `latest` tag, which may not exist—and because the loop above has verified all tags, the check is redundant anyway.

**Comment by runcom** [comment]
mmm it isn't called cause https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L81

**Comment by runcom** [comment]
> It seems that this will default to the latest tag

not sure about this, the actual call to the deamon is with "?tag=" so empty

**Comment by mtrmac** [comment]
> mmm it isn't called cause https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L81

Ah, missed that. Sorry.

**Comment by mtrmac** [comment]
> not sure about this, the actual call to the deamon is with "?tag=" so empty

ISTM this would end up in `distribution/distribution/reference/reference.go:getBestReference` which drops the empty tag, and then eventually `docker/docker/reference/reference.go:WithDefaultTag` would be called by `docker/docker/reference/store.go:store.Get`, but the code never reaches this path so this doesn’t matter.
