### ISSUE TITLE
Suspicious logic in ref.Hostname() == "docker.io" case

### ISSUE THREAD

**Issue by mtrmac** [runcom/rhel-push-plugin#2]
https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L86:
```
			if len(registries) != 0 {
				if registries[0] == "docker.io" {
					goto noallow
				}
			}
			goto noallow
```

- The `if` sequence appears redundant.
- (Assuming that the `if` is necessary:) Why is `registries[0]` special and others can be ignored? This should have at least a comment.

(Also, why both `strings.HasPrefix` and the `ref.Hostname` check? I may be naive but it seems there should be a single definite way to get the docker registry identity that will be used for a particular name.)

**Comment by runcom** [comment]
> This should have at least a comment.

I removed it in https://github.com/runcom/rhel-push-plugin/commit/1eac1988076733b81fc0957e6682ea3b59545e09#diff-70e973989f81df39acd35aa417b206bcL91

**Comment by runcom** [comment]
> (Also, why both strings.HasPrefix and the ref.Hostname check? I may be naive but it seems there should be a single definite way to get the docker registry identity that will be used for a particular name.)

the first is a fast check for our projectatomic/docker fork, and we're not going to actually transform the image string into a reference object

**Comment by runcom** [comment]
> The if sequence appears redundant.

I could have done a `&&` but I prefer that - also, the `len` check is necessary since:
```
panic: runtime error: index out of range
```

**Comment by runcom** [comment]
ref.Hostname() == "docker.io" is also needed because after the ref parse it gets appended automatically if no hostname is provided with the image

**Comment by mtrmac** [comment]
> > The if sequence appears redundant.

> I could have done a && but I prefer that

I don’t mean that the two nested `if`s are redundant, but that in `if … { $action } ; $action` all of the `if` makes no difference.

**Comment by mtrmac** [comment]
> we're not going to actually transform the image string into a reference object

`reference.ParseNamed` seems cheap enough (e.g. no IO); is the minor difference in speed really worth worrying about `strings.HasPrefix` and `ref.HostName` having different semantics?

**Comment by runcom** [comment]
removed HasPrefix case and added a comment on registries[0], pls check in master

**Comment by mtrmac** [comment]
AFAICS in https://github.com/runcom/rhel-push-plugin/blob/master/plugin.go#L82 , lines 82–89 make no difference and can be removed; the outcome is “operation prohibited” in any case per line 91.

**Comment by mtrmac** [comment]
… so either drop lines 82–89, or add a missing “allow” path somewhere in there.

**Comment by runcom** [comment]
if someone does:
```
docker push runcom/testrhelbased
```
`ref.Hostname()` is equal to `docker.io` after `ParseNamed` *BUT* lines 77-89 handle the case where the plugin is talking to a projectatomic/docker binary which can be configured with additional registries, say yourregistry.com, so that if you run the docker push above, docker pushes to yourregistry.com/runcom/testrhelbased. Our docker exposes the registries configured at daemon options and the check at lines 77-89 are there to ensure that the first registry is not docker.io when pushing unqualified images, OR otherwise, line 90 handle to default docker binary case.

Sorry @mtrmac, what I'm still missing..

**Comment by mtrmac** [comment]
I may just be overlooking something: assume execution gets to line 82, is there any way for any operation to be allowed? AFAICS it will always be prohibited, either by line 87 or line 91 – but in the end it makes no difference which of these is chosen, so the `if` case makes no difference to the eventual output.

Just guessing, did you mean to write
```
if ref.Hostname() == "docker.io" {
    goto noallow
}
registries := …
if $registries_point_to_docker.io {
   goto noallow
}
```

instead of nesting the two cases?

**Comment by runcom** [comment]
alright, I was missing an `goto allow` case in case the first registry isn't `docker.io`

**Comment by mtrmac** [comment]
Ah, OK.

Do the “additional registries” always override the hostname within the pushed reference, or are they just the default registry to use for non-hostname references? The code currently implements the former, which seems surprising.

**Comment by runcom** [comment]
> or are they just the default registry to use for non-hostname references

this one

**Comment by mtrmac** [comment]
>>  or are they just the default registry to use for non-hostname references

> this one

… and due to how `github.com/docker/docker/reference` `namedRef.Hostname` works, non-hostname references will return `"docker.io"` for the value, so we do go through this path (and there is no convenient API to tell whether the `"docker.io"` reference was explicit or implicit with this object). That seems pretty ugly but I can’t find a cleaner way to do this. (Linking also to `projectatomic/docker` to directly get the `projectatomic/docker` semantics would not work because the relevant commit https://github.com/projectatomic/docker/commit/0f2a2a96dafd266a43a09cb62d65578a41f6cb2d#diff-43b9672f67b9de1639f9c1a35193add6R167 does not live on the master branch.)

This would be worth more detailed comments at least, and preferably tests. Something like:

```
// ref.Hostname() uses the docker/docker/reference implementation, which automatically
// maps unspecified hostname to reference.DefaultHostname. So this `if` will match
// both explicitly pushing images to `docker.io` and pushing images to the default registry
// with the projectatomic/docker codebase.
		if ref.Hostname() == "docker.io" {
			registries, err := p.getAdditionalDockerRegistries()
			if err != nil {
				return authorization.Response{Err: err.Error()}
			}
	if len(registries) != 0 {
// We have a projectatomic/docker implementation: pushing without specifying a host name
// automatically uses one of the just discovered registries.
…
		}
// We have a docker/docker implementation; ref.Hostname() will be used, whether it is by being
// explicitly specified or by defaulting to it.
```

The above at least documents how I now _think_ it works, without testing it myself.

And if that is correct, the code is incorrectly handling the `projectatomic/docker` case when pushing to an explicit `docker.io/$name`: the code decides based on `registries[0]` but the push will happen to `docker.io` regardless, and should be rejected.

**Comment by runcom** [comment]
> And if that is correct, the code is incorrectly handling the projectatomic/docker case when pushing to an explicit docker.io/$name: the code decides based on registries[0] but the push will happen to docker.io regardless, and should be rejected.

I'll try to explain my points and logic I *think* I've implemented
The logic is, given the plugin is activated:

**case docker/docker daemon**
- if the image is not rhel based and qualified-> allow pushing
- if the image is not rhel based and unqualified -> allow pushing
- if the image is rhel based and qualified with docker.io -> disallow pushing
- if the image is rhel based and unqualified -> disallow pushing

**case projectatomic/docker daemon with additional registries REST route and 1 additional registry configured at myregistry.com:5000**
- if the image is not rhel based and qualified-> allow pushing
- if the image is not rhel based and unqualified -> allow pushing  (it goes to myregistry.com:5000)
- if the image is rhel based and qualified with docker.io -> disallow pushing **(I missed this now and this is why I had the strings.HasPrefix before anything)**
- if the image is rhel based and qualified with myregistry.com:5000 -> allow pushing
- if the image is rhel based and unqualified -> allow pushing (it goes to myregistry.com:5000)

ack about better comment, thanks

**Comment by mtrmac** [comment]
> if the image is rhel based and qualified with docker.io -> disallow pushing **
AFAICS this will go through lines 76 (true), 82 (true), 86 (false), 89, and actually allow.

**Comment by mtrmac** [comment]
https://github.com/runcom/rhel-push-plugin/commit/6fd5afc331df16c7c2b50c319f60ba7247027387#diff-70e973989f81df39acd35aa417b206bcR90
Comment needs updating: due to the `strings.HasPrefix()` check above, we now know that the repository name does not contain a host name.

https://github.com/runcom/rhel-push-plugin/commit/6fd5afc331df16c7c2b50c319f60ba7247027387#diff-70e973989f81df39acd35aa417b206bcR95
Doesn’t this comment belong inside the `len(registries != 0)` case?

**Comment by mtrmac** [comment]
ACK on the logic and flow.
